# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: banking system CI & CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check server
        run: pwd && ls -al

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: check server
        run: pwd && ls -al

      - name: start scp script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASS }}
          port: ${{ secrets.NCP_PORT }}
          source: "docker, script"
          target: "./deploy"
          strip_components: 1

      - name: run shell
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.NCP_HOST}}
          username: ${{secrets.NCP_USERNAME}}
          password: ${{secrets.NCP_PASS}}
          port: ${{secrets.NCP_PORT}}
          script: |
            cd ./deploy && chmod +x run.sh && sh run.sh