# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: banking system CI & CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check server
        run: ls -al

      - name: create folder
        run: mkdir ~/dist

      - name: copy script docs
        run: cp ./script ./dist

      - name: copy docker docs
        run: cp ./docker ./dist

      - name: check server
        run: cd dist && ls -al

      - name: start scp script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASS }}
          port: ${{ secrets.NCP_PORT }}
          source: "dist/"
          target: "./"
          strip_components: 1